language: R
warnings_are_errors: true
sudo: false
cache: packages

addons:
    apt:
        packages:
            - valgrind

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
